---
title: Yingxi Ji
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    categories: ''
    layout: project

url: http://jiyingxi.com/
permalink: "/:title/index.html"
legal: "© Sabrina yingxi ji 2019"
Linkedin: https://www.linkedin.com/in/yingxi-ji-027a1ba8
Instagram: Sabritism
email: yingxiji1992@gmail.com
sass:
  style: compressed
exclude:
- ".scss"
- README.md
- node_modules
- gruntfile.js
- package.json
